apiVersion: v1
kind: Service
metadata:
  name: gpu-benchmark-api
spec:
  selector:
    app: gpu-benchmark-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP

